conda-forge/mne-feedstock

recipe/meta.yaml
cc @jakirkham, this was the reason for https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/276681990. we should have better error handling
=> Fix maintainers

README.md, recipe/meta.yaml
=> Add python-picard dependency

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/win_64_.yaml, .scripts/run_osx_build.sh, README.md, azure-pipelines.yml, recipe/meta.yaml
=> New attempt to add an mne-base package

recipe/meta.yaml
=> Add numba dependency again

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .gitattributes, .scripts/build_steps.sh, .scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
=> MAINT: Bump to 0.24

recipe/meta.yaml
=> Pin pooch to >=1.5, add setuptools dep, add pip check test

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, recipe/meta.yaml
Checklist
Added traitlets dependency needed for `mne coreg`
=> add traitlets dependency

.ci_support/linux_64_.yaml, LICENSE.txt, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Add development builds

recipe/meta.yaml
=> Remove cupy dependency

recipe/meta.yaml
Forgot to tick the build number in #89 (it was in the checklist and I missed it :facepalm: !)
=> FIX: Tick build

recipe/meta.yaml
=> MAINT: Bump version

README.md, recipe/meta.yaml
Checklist
Now that https://github.com/conda-forge/eeglabio-feedstock/ is being created we can move forward with this. It should fail for now until the project actually gets created, built, and hits CDNs hopefully later today. I'll mark as automerge and restart CIs in a few hours.
=> ENH: Add eeglabio

recipe/meta.yaml
=> MAINT: Bump to 1.0.3

.circleci/config.yml, .github/workflows/automerge.yml, .github/workflows/webservices.yml, README.md, conda-forge.yml, recipe/menu/menu.json, recipe/menu/open_prompt.applescript, recipe/menu/open_prompt.bat, recipe/menu/open_prompt.sh, recipe/meta.yaml
=> Bump to 1.1dev0

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/win_64_.yaml, .circleci/config.yml, .scripts/run_osx_build.sh, README.md, azure-pipelines.yml, recipe/meta.yaml
Otherwise, the Dock icons etc won't be set!
Unfortunately, this makes the `mne` package non-`noarch` :(
(`mne-base` does remain `noarch`, though!)
Checklist
=> Depend on pyobjc-framework-cocoa on macOS

.azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
Checklist
@hoechenberger I want to try building a 1.2dev0 installer and this seemed like the first step, can you approve and/or mark automerge if it seems correct?
=> MAINT: Update 1.2dev0

recipe/meta.yaml
=> bump to 1.2

recipe/meta.yaml
=> update version, hash, and dependencies

.azure-pipelines/azure-pipelines-win.yml, recipe/meta.yaml
=> MAINT: Bump to 1.3.1

.azure-pipelines/azure-pipelines-win.yml, .circleci/config.yml, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
Checklist
Doing this to make sure we get the `setuptools_scm` infrastructure right during release
=> ENH: Update dev

recipe/meta.yaml
Checklist
Following https://github.com/mne-tools/mne-python/pull/11696
=> Update minimum requirement for matplotlib and scipy

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/run_osx_build.sh, recipe/meta.yaml
Checklist
Will fail until we actually release
=> MAINT: Update to 1.5

.gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, recipe/meta.yaml
=> MAINT: 1.6.1

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, build-locally.py, recipe/meta.yaml
=> MAINT: Bump to 1.7.0

recipe/meta.yaml
=> Try to use `hatchling` exclusively for building

.scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
=> MAINT: bump to 1.7.1

.ci_support/linux_64_build_variantpyqtpython3.10.____cpython.yaml, .ci_support/linux_64_build_variantpyqtpython3.11.____cpython.yaml, .ci_support/linux_64_build_variantpyqtpython3.12.____cpython.yaml, .ci_support/linux_64_build_variantpyqtpython3.9.____cpython.yaml, .ci_support/linux_64_build_variantpyside6python3.10.____cpython.yaml, .ci_support/linux_64_build_variantpyside6python3.11.____cpython.yaml, .ci_support/linux_64_build_variantpyside6python3.12.____cpython.yaml, .ci_support/linux_64_build_variantpyside6python3.9.____cpython.yaml, .ci_support/osx_64_build_variantpyqtpython3.10.____cpython.yaml, .ci_support/osx_64_build_variantpyqtpython3.11.____cpython.yaml, .ci_support/osx_64_build_variantpyqtpython3.12.____cpython.yaml, .ci_support/osx_64_build_variantpyqtpython3.9.____cpython.yaml, .ci_support/osx_64_build_variantpyside6python3.10.____cpython.yaml, .ci_support/osx_64_build_variantpyside6python3.11.____cpython.yaml, .ci_support/osx_64_build_variantpyside6python3.12.____cpython.yaml, .ci_support/osx_64_build_variantpyside6python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> MAINT: Bump
